src/Entity/Activities.php
<?php

namespace App\Entity;

use App\Repository\ActivitiesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ActivitiesRepository::class)]
class Activities
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_url = null;

    #[ORM\Column]
    private ?bool $outside = null;

    #[ORM\Column]
    private ?bool $home_based = null;

    #[ORM\Column]
    private ?\DateTime $start_time = null;

    #[ORM\Column]
    private ?\DateTime $end_time = null;

    #[ORM\Column]
    private ?float $fullcost = null;

    #[ORM\Column]
    private ?float $discounted_price = null;

    #[ORM\Column]
    private ?int $availability_fullcost = null;

    #[ORM\Column(nullable: true)]
    private ?int $availability_discounted_price = null;

    #[ORM\Column]
    private ?int $remaining_availability_fullcost = null;

    #[ORM\Column(nullable: true)]
    private ?int $remaining_availability_discounted_price = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $recurrence = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $specific_note = null;



    #[ORM\ManyToOne(inversedBy: 'activities')]
    private ?theme $theme = null;

    #[ORM\ManyToOne(inversedBy: 'Activities')]
    private ?ProfessorUser $professorUser = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): static
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function isOutside(): ?bool
    {
        return $this->outside;
    }

    public function setOutside(bool $outside): static
    {
        $this->outside = $outside;

        return $this;
    }

    public function isHomeBased(): ?bool
    {
        return $this->home_based;
    }

    public function setHomeBased(bool $home_based): static
    {
        $this->home_based = $home_based;

        return $this;
    }

    public function getStartTime(): ?\DateTime
    {
        return $this->start_time;
    }

    public function setStartTime(\DateTime $start_time): static
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getEndTime(): ?\DateTime
    {
        return $this->end_time;
    }

    public function setEndTime(\DateTime $end_time): static
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getFullcost(): ?float
    {
        return $this->fullcost;
    }

    public function setFullcost(float $fullcost): static
    {
        $this->fullcost = $fullcost;

        return $this;
    }

    public function getDiscountedPrice(): ?float
    {
        return $this->discounted_price;
    }

    public function setDiscountedPrice(?float $discounted_price): static
    {
        $this->discounted_price = $discounted_price;

        return $this;
    }

    public function getAvailabilityFullcost(): ?int
    {
        return $this->availability_fullcost;
    }

    public function setAvailabilityFullcost(int $availability_fullcost): static
    {
        $this->availability_fullcost = $availability_fullcost;

        return $this;
    }

    public function getAvailabilityDiscountedPrice(): ?int
    {
        return $this->availability_discounted_price;
    }

    public function setAvailabilityDiscountedPrice(?int $availability_discounted_price): static
    {
        $this->availability_discounted_price = $availability_discounted_price;

        return $this;
    }

    public function getRemainingAvailabilityFullcost(): ?int
    {
        return $this->remaining_availability_fullcost;
    }

    public function setRemainingAvailabilityFullcost(int $remaining_availability_fullcost): static
    {
        $this->remaining_availability_fullcost = $remaining_availability_fullcost;

        return $this;
    }

    public function getRemainingAvailabilityDiscountedPrice(): ?int
    {
        return $this->remaining_availability_discounted_price;
    }

    public function setRemainingAvailabilityDiscountedPrice(?int $remaining_availability_discounted_price): static
    {
        $this->remaining_availability_discounted_price = $remaining_availability_discounted_price;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getRecurrence(): ?string
    {
        return $this->recurrence;
    }

    public function setRecurrence(?string $recurrence): static
    {
        $this->recurrence = $recurrence;

        return $this;
    }

    public function getSpecificNote(): ?string
    {
        return $this->specific_note;
    }

    public function setSpecificNote(?string $specific_note): static
    {
        $this->specific_note = $specific_note;

        return $this;
    }



    public function getTheme(): ?Theme
    {
        return $this->theme;
    }

    public function setTheme(?Theme $theme): static
    {
        $this->theme = $theme;

        return $this;
    }

    public function getProfessorUser(): ?ProfessorUser
    {
        return $this->professorUser;
    }

    public function setProfessorUser(?ProfessorUser $professorUser): static
    {
        $this->professorUser = $professorUser;

        return $this;
    }
}

src/Entity/ProfessorUser.php
<?php

namespace App\Entity;

use App\Repository\ProfessorUserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use function PHPUnit\Framework\exactly;

#[ORM\Entity(repositoryClass: ProfessorUserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class ProfessorUser implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]

    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\Email]
    #[Assert\NotBlank]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    #[Assert\NotBlank(message: 'Veuillez choisir au moins un rôle.')]
    #[Assert\Choice(
        choices: ['ROLE_PROFESSOR', 'ROLE_USER', 'ROLE_ORGANISATION'],
        multiple: true
    )]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank]
    #[Assert\NotCompromisedPassword]
    #[Assert\Length(min: 4, minMessage: 'Le mot de passe doit contenir 4 caractères au minimum')]
    private ?string $password = null;



    #[ORM\Column(length: 11)]
    #[Assert\NotBlank]
    #[Assert\Length(9)]
    private ?string $company_identification_number = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 20)]

    private ?string $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $profil_picture = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    #[Assert\length(min: 50, minMessage: 'Ne soyez pas timide ! Votre description doit contenir au moins 50 caractères !')]
    private ?string $presentation = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $adress = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $city = null;

    /**
     * @var Collection<int, Activities>
     */
    #[ORM\OneToMany(targetEntity: Activities::class, mappedBy: 'professorUser')]
    private Collection $Activities;

    /**
     * @var Collection<int, Evaluation>
     */
    #[ORM\OneToMany(targetEntity: Evaluation::class, mappedBy: 'professorUser')]
    private Collection $Evaluations;

    public function __construct()
    {
        $this->Activities = new ArrayCollection();
        $this->Evaluations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCompanyIdentificationNumber(): ?string
    {
        return $this->company_identification_number;
    }

    public function setCompanyIdentificationNumber(string $company_identification_number): static
    {
        $this->company_identification_number = $company_identification_number;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getProfilPicture(): ?string
    {
        return $this->profil_picture;
    }

    public function setProfilPicture(string $profil_picture): static
    {
        $this->profil_picture = $profil_picture;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): static
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection<int, Activities>
     */
    public function getActivities(): Collection
    {
        return $this->Activities;
    }

    public function addActivity(Activities $activity): static
    {
        if (!$this->Activities->contains($activity)) {
            $this->Activities->add($activity);
            $activity->setProfessorUser($this);
        }

        return $this;
    }

    public function removeActivity(Activities $activity): static
    {
        if ($this->Activities->removeElement($activity)) {
            // set the owning side to null (unless already changed)
            if ($activity->getProfessorUser() === $this) {
                $activity->setProfessorUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Evaluation>
     */
    public function getEvaluations(): Collection
    {
        return $this->Evaluations;
    }

    public function addEvaluation(Evaluation $evaluation): static
    {
        if (!$this->Evaluations->contains($evaluation)) {
            $this->Evaluations->add($evaluation);
            $evaluation->setProfessorUser($this);
        }

        return $this;
    }

    public function removeEvaluation(Evaluation $evaluation): static
    {
        if ($this->Evaluations->removeElement($evaluation)) {
            // set the owning side to null (unless already changed)
            if ($evaluation->getProfessorUser() === $this) {
                $evaluation->setProfessorUser(null);
            }
        }

        return $this;
    }
}

src/Form/ProfessorForm.php
<?php

namespace App\Form;

use App\Entity\ProfessorUser;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class ProfessorForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class)
            ->add('roles', ChoiceType::class, [
                'choices' => [
                    'Professeur' => 'ROLE_PROFESSOR',
                    'Utilisateur' => 'ROLE_USER',
                    'Organisation' => 'ROLE_ORGANISATION',
                ],
                'multiple' => true,
                'expanded' => true,
                'label' => 'Vous êtes',
                'required' => true,
            ])
            ->add('password', PasswordType::class)

            ->add('company_identification_number', IntegerType::class)
            ->add('name', TextType::class)
            ->add('firstname', TextType::class)
            ->add('phone', TelType::class)
            ->add('profile_picture', FileType::class, [
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new Image()
                ]
            ])
            ->add('presentation', TextareaType::class)
            ->add('adress', TextType::class)
            ->add('city', TextType::class)
            ->add('Souscrire', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProfessorUser::class,
        ]);
    }
}

src/Controller/ProfessorsController.php
<?php

namespace App\Controller;


use App\Entity\ProfessorUser;
use App\Repository\ProfessorUserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Knp\Component\Pager\PaginatorInterface;

final class ProfessorsController extends AbstractController
{
    #[Route('/professors', name: 'app_professors')]
    public function index(
        ProfessorUserRepository $profRepo,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $query = $profRepo->createQueryBuilder('p')
            ->orderBy('p.name', 'ASC')
            ->getQuery();

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            8
        );

        return $this->render('professors/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    #[Route('/professors/{id}', name: 'app_professors_show')]
    public function show(ProfessorUser $prof): Response
    {
        return $this->render('professors/show.html.twig', [
            'professorUser' => $prof,
        ]);
    }
}

templates/professors/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Liste des Professeurs
{% endblock %}

{% block body %}
  <h1 style="text-align: center; margin-top: 30px;">Nos Professeurs</h1>

  <div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 20px; padding: 30px;">
    {% for prof in pagination %}
      <div style="
                width: 300px;
                border: 1px solid #ddd;
                border-radius: 10px;
                box-shadow: 0 4px 8px rgba(0,0,0,0.1);
                overflow: hidden;
                background-color: #fff;
                display: flex;
                flex-direction: column;
                justify-content: space-between;
            ">
        <div style="height: 200px; overflow: hidden;">
          <img src="{{ asset(prof.profilPicture ? 'uploads/' ~ prof.profilPicture : 'images/default-profile.jpg') }}" alt="Photo de {{ prof.firstname }} {{ prof.name }}" style="width: 100%; height: 100%; object-fit: cover;" />
        </div>

        <div style="padding: 15px;">
          <h3 style="margin: 0;">{{ prof.firstname }} {{ prof.name }}</h3>
          <p style="margin: 5px 0; color: #666;">{{ prof.email }}</p>
          <p style="margin: 5px 0;">
            <strong>Téléphone :</strong> {{ prof.phone }}
          </p>
          <p style="margin: 5px 0;">
            <strong>Ville :</strong> {{ prof.city }}
          </p>
          <p style="margin-top: 10px; font-size: 0.9em; color: #444;">{{ (prof.presentation|length) > 100 ? (prof.presentation|slice(0, 100)) ~ '...' : prof.presentation }}</p>
        </div>

        <div style="padding: 10px 15px; text-align: right;">
          <a href="{{ path('app_professors_show', { id: prof.id }) }}" style="
                        padding: 6px 12px;
                        background-color: #FF8C42;
                        color: white;
                        text-decoration: none;
                        border-radius: 5px;
                        font-size: 0.9em;
                    ">Voir le profil</a>
        </div>
      </div>
    {% else %}
      <p>Aucun professeur trouvé.</p>
    {% endfor %}
  </div>

  <div style="text-align: center;">{{ knp_pagination_render(pagination) }}</div>
{% endblock %}

templates/professors/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Profil du professeur
{% endblock %}

{% block body %}
  <div style="max-width: 900px; margin: 2rem auto; padding: 2rem; background-color: #fff; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); font-family: Arial, sans-serif;">
    <div style="display: flex; align-items: center; gap: 2rem;">
      {% if professorUser.profilPicture %}
        <img src="{{ asset('uploads/' ~ professorUser.profilPicture) }}" alt="Photo de profil" style="width: 140px; height: 140px; border-radius: 50%; object-fit: cover; border: 3px solid #FF8C42;" />
      {% else %}
        <div style="width: 140px; height: 140px; border-radius: 50%; background: #eee; display: flex; align-items: center; justify-content: center; font-size: 3rem;">👤</div>
      {% endif %}

      <div>
        <h2 style="margin: 0;">{{ professorUser.firstname }} {{ professorUser.name }}</h2>
        <p style="color: #666; margin: 0.2rem 0;">{{ professorUser.email }}</p>
        <p style="color: #666;">📞 {{ professorUser.phone }}</p>
      </div>
    </div>

    <hr style="margin: 2rem 0; border: none; border-top: 1px solid #ddd;" />

    <h3 style="color: #FF8C42;">Présentation</h3>
    <p>{{ professorUser.presentation }}</p>

    <h3 style="color: #FF8C42; margin-top: 2rem;">Coordonnées</h3>
    <p>🏢 {{ professorUser.adress }}, {{ professorUser.city }}</p>
    <p>SIRET : {{ professorUser.companyIdentificationNumber }}</p>

    <hr style="margin: 2rem 0; border: none; border-top: 1px solid #ddd;" />

    <h3 style="color: #FF8C42;">Activités proposées</h3>
    {% if (professorUser.activities|length) > 0 %}
      <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1rem;">
        {% for activity in professorUser.activities %}
          <div style="border: 1px solid #eee; border-radius: 8px; padding: 1rem; background-color: #fafafa;">
            <h4 style="margin: 0 0 0.5rem 0;">{{ activity.title }}</h4>
            <p style="margin: 0; font-size: 0.9rem;">📍 {{ activity.location }}</p>
            <p style="margin: 0; font-size: 0.9rem;">🕒 {{ activity.startTime|date('d/m/Y H:i') }}</p>
            <a href="{{ path('app_activities_show', { id: activity.id }) }}" style="display: inline-block; margin-top: 0.5rem; font-size: 0.9rem; color: #FF8C42;">Voir l'activité →</a>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>Aucune activité enregistrée pour ce professeur.</p>
    {% endif %}
  </div>
{% endblock %}